-- Snowflake 데이터베이스 및 3-Layer 스키마 생성
-- Layer 1: RAW       — 크롤링 원본 그대로
-- Layer 2: STAGING   — 정제/정규화
-- Layer 3: ANALYTICS — 시각화/분석용 집계

CREATE DATABASE IF NOT EXISTS COMPUTER_PRICE;
USE DATABASE COMPUTER_PRICE;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
