-- =====================================================
-- 004_schema_refactor.sql
-- 목적: 테이블명 정리, 컬럼명 명확화, DIM 테이블 비정규화
-- 대상: 기존 COMPUTER_PRICE 데이터베이스에 순서대로 실행
-- =====================================================

USE DATABASE COMPUTER_PRICE;

-- =====================================================
-- Step 1: 테이블 이름 변경
-- =====================================================

USE SCHEMA RAW;
ALTER TABLE RAW_CRAWLED_PRICES RENAME TO CRAWLED_PRICES;

USE SCHEMA STAGING;
ALTER TABLE STG_PRODUCTS      RENAME TO PRODUCTS;
ALTER TABLE STG_DAILY_PRICES  RENAME TO PRICE_HISTORY;
ALTER TABLE STG_LATEST_PRICES RENAME TO LATEST_PRICES;
ALTER TABLE STG_ALERTS        RENAME TO PRICE_ALERTS;
ALTER TABLE USER_WATCH_PRODUCTS RENAME TO WATCHLIST;

USE SCHEMA ANALYTICS;
ALTER TABLE DAILY_SUMMARY  RENAME TO DAILY_PRICE_STATS;
ALTER TABLE WEEKLY_SUMMARY RENAME TO WEEKLY_PRICE_STATS;

-- =====================================================
-- Step 2: 컬럼 이름 변경
-- =====================================================

USE SCHEMA STAGING;
-- PRODUCTS.NAME → PRODUCT_NAME (너무 generic)
ALTER TABLE PRODUCTS RENAME COLUMN NAME TO PRODUCT_NAME;

USE SCHEMA ANALYTICS;
-- PRODUCT_STATS: 역할이 명확하게 드러나도록 변경
ALTER TABLE PRODUCT_STATS RENAME COLUMN OVERALL_AVG   TO AVG_PRICE;
ALTER TABLE PRODUCT_STATS RENAME COLUMN ALL_TIME_LOW  TO MIN_PRICE_EVER;
ALTER TABLE PRODUCT_STATS RENAME COLUMN ALL_TIME_HIGH TO MAX_PRICE_EVER;
ALTER TABLE PRODUCT_STATS RENAME COLUMN FIRST_SEEN    TO FIRST_CRAWLED_AT;
ALTER TABLE PRODUCT_STATS RENAME COLUMN LAST_SEEN     TO LAST_CRAWLED_AT;

-- =====================================================
-- Step 3: DIM 테이블 비정규화 (SITE_ID/CATEGORY_ID → VARCHAR)
-- =====================================================

USE SCHEMA STAGING;

-- 3a: 새 VARCHAR 컬럼 추가 (처음엔 NULL 허용)
ALTER TABLE PRODUCTS ADD COLUMN SITE     VARCHAR(50);
ALTER TABLE PRODUCTS ADD COLUMN CATEGORY VARCHAR(100);

-- 3b: DIM_SITES.DISPLAY_NAME 값으로 채우기
UPDATE PRODUCTS
SET SITE = (
    SELECT DISPLAY_NAME FROM DIM_SITES WHERE SITE_ID = PRODUCTS.SITE_ID
);

-- 3c: DIM_CATEGORIES.NAME 값으로 채우기
UPDATE PRODUCTS
SET CATEGORY = (
    SELECT NAME FROM DIM_CATEGORIES WHERE CATEGORY_ID = PRODUCTS.CATEGORY_ID
);

-- 3d: NOT NULL 제약 추가
ALTER TABLE PRODUCTS ALTER COLUMN SITE     SET NOT NULL;
ALTER TABLE PRODUCTS ALTER COLUMN CATEGORY SET NOT NULL;

-- 3e: 기존 UNIQUE 제약 삭제 (SITE_ID + NAME 기반)
ALTER TABLE PRODUCTS DROP CONSTRAINT UQ_STG_PRODUCTS_SITE_NAME;

-- 3f: FK 컬럼 삭제
ALTER TABLE PRODUCTS DROP COLUMN SITE_ID;
ALTER TABLE PRODUCTS DROP COLUMN CATEGORY_ID;

-- 3g: 새 UNIQUE 제약 추가 (SITE + PRODUCT_NAME 기반)
ALTER TABLE PRODUCTS ADD CONSTRAINT UQ_PRODUCTS UNIQUE (SITE, PRODUCT_NAME);

-- 3h: DIM 테이블 삭제
DROP TABLE DIM_SITES;
DROP TABLE DIM_CATEGORIES;
