-- WATCHLIST에 SITE 컬럼 추가
-- 기존 다나와 항목은 DEFAULT 'danawa'로 자동 설정됨

USE DATABASE COMPUTER_PRICE;
USE SCHEMA STAGING;

ALTER TABLE WATCHLIST ADD COLUMN IF NOT EXISTS SITE VARCHAR(20) NOT NULL DEFAULT 'danawa';
